-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 12:42:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controle_grade
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controle_grade` ;

-- -----------------------------------------------------
-- Schema controle_grade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle_grade` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `controle_grade` ;

-- -----------------------------------------------------
-- Table `controle_grade`.`ambiente_fisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`ambiente_fisico` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`ambiente_fisico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sala` VARCHAR(45) NOT NULL,
  `predio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `unico` ON `controle_grade`.`ambiente_fisico` (`predio` ASC, `sala` ASC);


-- -----------------------------------------------------
-- Table `controle_grade`.`ambiente_virtual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`ambiente_virtual` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`ambiente_virtual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME(6) NOT NULL,
  `data_fim` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`ambiente_virtual` (`data_inicio` ASC, `data_fim` ASC);


-- -----------------------------------------------------
-- Table `controle_grade`.`atribuicao_docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`atribuicao_docente` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`atribuicao_docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  `docente_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_curso_has_disciplina_curso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `controle_grade`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `controle_grade`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atribuicao_docente_semestre1`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `controle_grade`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atribuicao_docente_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `controle_grade`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atribuicao_docente_Turma1`
    FOREIGN KEY (`turno_id`)
    REFERENCES `controle_grade`.`turno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_curso_has_disciplina_disciplina1_idx` ON `controle_grade`.`atribuicao_docente` (`disciplina_id` ASC);

CREATE INDEX `fk_curso_has_disciplina_curso_idx` ON `controle_grade`.`atribuicao_docente` (`curso_id` ASC);

CREATE INDEX `fk_atribuicao_docente_semestre1_idx` ON `controle_grade`.`atribuicao_docente` (`semestre_id` ASC);

CREATE INDEX `fk_atribuicao_docente_Turma1_idx` ON `controle_grade`.`atribuicao_docente` (`turno_id` ASC);

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`atribuicao_docente` (`curso_id` ASC, `disciplina_id` ASC, `semestre_id` ASC, `turno_id` ASC);


-- -----------------------------------------------------
-- Table `controle_grade`.`atribuicao_horario_presencial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`atribuicao_horario_presencial` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`atribuicao_horario_presencial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atribuicao_docente_id` INT NOT NULL,
  `horario_presencial_id` INT NOT NULL,
  `ambiente_fisico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_horario_disciplina_atribuicao_docente1`
    FOREIGN KEY (`atribuicao_docente_id`)
    REFERENCES `controle_grade`.`atribuicao_docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_disciplina_horario_presencial1`
    FOREIGN KEY (`horario_presencial_id`)
    REFERENCES `controle_grade`.`horario_presencial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atribuicao_horario_presencial_ambiente_fisico1`
    FOREIGN KEY (`ambiente_fisico_id`)
    REFERENCES `controle_grade`.`ambiente_fisico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_horario_disciplina_atribuicao_docente1_idx` ON `controle_grade`.`atribuicao_horario_presencial` (`atribuicao_docente_id` ASC) ;

CREATE INDEX `fk_horario_disciplina_horario_presencial1_idx` ON `controle_grade`.`atribuicao_horario_presencial` (`horario_presencial_id` ASC) ;

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`atribuicao_horario_presencial` (`atribuicao_docente_id` ASC, `horario_presencial_id` ASC) ;

CREATE INDEX `fk_atribuicao_horario_presencial_ambiente_fisico1_idx` ON `controle_grade`.`atribuicao_horario_presencial` (`ambiente_fisico_id` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`atribuicao_horario_virtual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`atribuicao_horario_virtual` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`atribuicao_horario_virtual` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atribuicao_docente_id` INT NOT NULL,
  `ambiente_virtual_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_atribuicao_horario_virtual_atribuicao_docente1`
    FOREIGN KEY (`atribuicao_docente_id`)
    REFERENCES `controle_grade`.`atribuicao_docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atribuicao_horario_virtual_ambiente_virtual1`
    FOREIGN KEY (`ambiente_virtual_id`)
    REFERENCES `controle_grade`.`ambiente_virtual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_atribuicao_horario_virtual_atribuicao_docente1_idx` ON `controle_grade`.`atribuicao_horario_virtual` (`atribuicao_docente_id` ASC) ;

CREATE INDEX `fk_atribuicao_horario_virtual_ambiente_virtual1_idx` ON `controle_grade`.`atribuicao_horario_virtual` (`ambiente_virtual_id` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`curso` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `duracao` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `controle_grade`.`curso` (`nome` ASC);


-- -----------------------------------------------------
-- Table `controle_grade`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`disciplina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `creditos` TINYINT(2) UNSIGNED NOT NULL,
  `carga_horaria` TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`disciplina` (`nome` ASC, `creditos` ASC);


-- -----------------------------------------------------
-- Table `controle_grade`.`docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`docente` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`docente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `contrato` TINYINT(1) NOT NULL,
  `email` VARCHAR(100) NULL,
  `lattes` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_grade`.`horario_presencial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`horario_presencial` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`horario_presencial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` VARCHAR(45) NOT NULL,
  `hora_final` VARCHAR(45) NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`horario_presencial` (`hora_inicio` ASC, `hora_final` ASC, `dia_semana` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`modalidade` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`modalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modalidade` VARCHAR(20) NOT NULL,
  `atribuicao_docente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_modalidade_atribuicao_docente1`
    FOREIGN KEY (`atribuicao_docente_id`)
    REFERENCES `controle_grade`.`atribuicao_docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_modalidade_atribuicao_docente1_idx` ON `controle_grade`.`modalidade` (`atribuicao_docente_id` ASC) ;

CREATE UNIQUE INDEX `unico` ON `controle_grade`.`modalidade` (`atribuicao_docente_id` ASC, `modalidade` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`semestre` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Unico` ON `controle_grade`.`semestre` (`ano` ASC, `numero` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`turno` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`turno` (
  `id` INT NOT NULL,
  `turno` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `turno_UNIQUE` ON `controle_grade`.`turno` (`turno` ASC) ;


-- -----------------------------------------------------
-- Table `controle_grade`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controle_grade`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controle_grade`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `nivel-acesso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `controle_grade`.`usuario` (`login` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
